---
title: "Detection of eco-evolutionary dynamics in metacommunities using Joint Species
  Distribution Models"
author:
  - Jelena H. Pantel^[Laboratoire Chrono-environnement,UMR 6249 CNRS-UFC, 16 Route de Gray, 25030 Besançon cedex, France, jelena.pantel@univ-fcomte.fr]
  - Ruben J. Hermann^[University of Duisburg-Essen, Universitätsstraße 5, 45141 Essen, Germany, ruben.hermann@uni-due.de]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
    latex_engine: xelatex
    extra_dependencies: ["float"]
    number_sections: true
  bookdown::html_document2: default
  word_document:
    reference_docx: docx_template.docx
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[L]{Author Pantel and Hermann}
- \fancyhead[R]{Detection of ecoevo dynamics}
- \usepackage{lineno}
- \linenumbers
linestretch: 2
link-citations: yes
linkcolor: blue
csl: the-american-naturalist.csl
bibliography: refs.bib
---

```{r setup,echo=FALSE,warning=FALSE,message=FALSE}
library(Hmsc)
```


\newpage

Title
===============================================================================

Detection of eco-evolutionary dynamics in metacommunities using Joint Species Distribution Models
    
Abstract
===============================================================================
  
XXXXX

Introduction
================================================================================

XXXXX

Methods
================================================================================

## Simulation model

We simulated growth and competition dynamics for a multi-species assemblage in a patchy landscape, with site variation in one environmental property.

### Environmental variation

Population growth for species in the metacommunity simulation follows a Leslie-Gower model (a discrete-time version of a Lotka-Volterra model [@Beverton1957] [@Leslie1958]). We consider the impact of trait evolution for growth using a discrete time quantitative genetic model of evolutionary rescue [@Gomulkiewicz1995]. The model for population size is as follows:

$$ N_{i,t+1} =\frac{\hat{W}e^ \frac{-[(\frac{w+(1-h^2)P} {P+w})(E-x_{i,t})]^2}{2(P+w)}N_{i,t}} {1 + \alpha_{ii}N_{i,t} + \sum_{j \neq i}^{S} \alpha_{ij}N_{j,t}} $$
where $N_i,t$ is the population size of species *i* at time *t*, \( \hat{W} \) is calculated as \( \hat{W}=W_{max}\sqrt(\frac{w}{P+w}) \), \(W_{max}\) is the species' maximum per-capita growth rate, *w* is the width of the Gaussian fitness function (which determines the strength of selection, as increasing values indicate a weaker reduction in fitness with distance from optimum trait value), *P* is the width of the distribution of the phenotype *x*, $h^2$ is the heritability of the trait *x*, *E* is the local environmental optimum trait value, $x_{i,t}$ is the trait value of species *i* at time *t*, $\alpha_{ii}$ is the intraspecific competition coefficient (the per capita impact of species *i* on itself) and $\alpha_{ij}$ is the interspecific competition coefficient. Populations have a critical density $N_c$, below which the population is subject to extinction due to demographic stochasticity at a probability of *p* [@Gomulkiewicz1995].


Results
===============================================================================

XXXX

Discussion
================================================================================

XXXXX


References
===============================================================================

<div id="refs"></div>

<a name="appendix">Figures & Tables</a>
================================================================================

